.TH NODELIST.BBS 5 "30 Jul 1995" "NCTU CSIE" "Kuhn\'s Utility Reference Manual"
.SH NAME
mkhistory \- MaKe History
.SH SYNOPSIS
.B mkhistory history-file
.SH DESCRIPTION
.PP
.I mkhistory 
can be used to reconstruct history dbz from history source file
if the original dbz files have been corrupted.
.SH OPTIONS
mkhistory history-source-file

.SH FILES and DIRECTORIES
.BR ~bbs/innd/history, ~bbs/innd/history.pag, ~bbs/innd/history.dir
.BR ~bbs/innd/innbbs.conf, ~bbs/innd/newsfeeds.bbs, ~bbs/innd/nodelist.bbs
.SH AUTHOR
Shih-Kun Huang (skhuang@csie.nctu.edu.tw)
.SH BUGS
.SH "SEE ALSO"
.BR newsfeeds.bbs (5), innbbsd (8), bntplink (8)
